{{- if .Values.ethMock.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "plinko-pir.fullname" . }}-eth-mock
  labels:
    {{- include "plinko-pir.componentLabels" (dict "component" "eth-mock" "root" .) | nindent 4 }}
spec:
  type: {{ .Values.ethMock.service.type }}
  ports:
    - port: {{ .Values.ethMock.service.port }}
      targetPort: rpc
      protocol: TCP
      name: rpc
  selector:
    {{- include "plinko-pir.componentSelectorLabels" (dict "component" "eth-mock" "root" .) | nindent 4 }}
{{- end }}
