{{- if and .Values.plinkoPirServer.enabled .Values.plinkoPirServer.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "plinko-pir.fullname" . }}-pir-server
  labels:
    {{- include "plinko-pir.componentLabels" (dict "component" "pir-server" "root" .) | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "plinko-pir.fullname" . }}-pir-server
  minReplicas: {{ .Values.plinkoPirServer.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.plinkoPirServer.autoscaling.maxReplicas }}
  metrics:
  {{- if .Values.plinkoPirServer.autoscaling.targetCPUUtilizationPercentage }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.plinkoPirServer.autoscaling.targetCPUUtilizationPercentage }}
  {{- end }}
  {{- if .Values.plinkoPirServer.autoscaling.targetMemoryUtilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.plinkoPirServer.autoscaling.targetMemoryUtilizationPercentage }}
  {{- end }}
{{- end }}
