{{- if .Values.plinkoUpdateService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "plinko-pir.fullname" . }}-update-service
  labels:
    {{- include "plinko-pir.componentLabels" (dict "component" "update-service" "root" .) | nindent 4 }}
spec:
  type: {{ .Values.plinkoUpdateService.service.type }}
  ports:
    - port: {{ .Values.plinkoUpdateService.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "plinko-pir.componentSelectorLabels" (dict "component" "update-service" "root" .) | nindent 4 }}
{{- end }}
