{{- if and .Values.rabbyWallet.enabled .Values.rabbyWallet.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "plinko-pir.fullname" . }}-rabby-wallet
  labels:
    {{- include "plinko-pir.componentLabels" (dict "component" "rabby-wallet" "root" .) | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "plinko-pir.fullname" . }}-rabby-wallet
  minReplicas: {{ .Values.rabbyWallet.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.rabbyWallet.autoscaling.maxReplicas }}
  metrics:
  {{- if .Values.rabbyWallet.autoscaling.targetCPUUtilizationPercentage }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.rabbyWallet.autoscaling.targetCPUUtilizationPercentage }}
  {{- end }}
{{- end }}
