{{- if .Values.rabbyWallet.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "plinko-pir.fullname" . }}-rabby-wallet
  labels:
    {{- include "plinko-pir.componentLabels" (dict "component" "rabby-wallet" "root" .) | nindent 4 }}
spec:
  type: {{ .Values.rabbyWallet.service.type }}
  ports:
    - port: {{ .Values.rabbyWallet.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "plinko-pir.componentSelectorLabels" (dict "component" "rabby-wallet" "root" .) | nindent 4 }}
{{- end }}
